name: NodeJS

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Node.js Build

    runs-on: ubuntu-latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v5

    - name: Use Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 24.x

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: HTML validator
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: .
